language: python
dist: bionic

python:
  - "3.6"
  - "3.7"
  - "3.8"
#  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 server
  - python3 server/test.py
